Improve select behaviour and styles
mercurymedia/elm-smart-select pull request #57
Opened 2024-06-11 10:07 UTC by markus-mind

2024-06-28 14:06 UTC, mschindlerMM requested changes
We need to document the changes for the user in the changelog. Also, we need to update the README.

2024-06-28 14:06 UTC, mschindlerMM commented on src/SingleSelectRemote.elm
> +--     = Prefix String
this can be removed

2024-06-28 14:11 UTC, mschindlerMM commented
Clicking the Clear button when the select is closed, opens it. That seems a bit strange to me.

2024-09-10 13:25 UTC, hingew approved these changes

2024-09-10 13:27 UTC, merged